#!/bin/bash
feature_type_list=(Frag)
input_size=(1200)
for i in {0..0}
do
    python ./DANN_run.py ${feature_type_list[i]} 1D ${input_size[i]} 2 20 /mnt/binf/eric/MDAB_AugResults/test /mnt/binf/eric/Mercury_Aug2023_new/Feature_all_Aug2023_DomainKAG9v1_SeqBatchAll.csv
done

